### ISSUE TITLE
Cannot access to postfixadmin, spam and rainloop

### ISSUE THREAD

**Issue by mervynlee94** [hardware/mailserver-rancher#2]
I have configured Traefik and everything is running fine and healthy. I already updated DNS record and checked them with DNS checker. However, I cannot reach these sites with message "This site can’t be reached". Any possible causes for it? Thanks!

**Comment by hardware** [comment]
Can you share your Traefik settings in Rancher panel ?

**Comment by mervynlee94** [comment]
Here is the exported config generated under traefik container. 

[compose.zip](https://github.com/hardware/mailserver-rancher/files/1969634/compose.zip)

Is that enough? Do I need to share you anything else? Thanks

**Comment by mervynlee94** [comment]
Okay it solved. Thanks
