### ISSUE TITLE
Regarding SSL

### ISSUE THREAD

**Issue by mervynlee94** [hardware/mailserver-rancher#3]
Following the steps in README, is that SSL will be generate automatically? I see that I have to insert certificate inside Traefik configuration on Rancher, is that the moment I have to do something on it? Because if I leave it blank, I can't access those postfixadmin and webmail with https

**Comment by hardware** [comment]
The SSL certificate is generated automatically when you doesn't provide a custom certificate : 

https://github.com/hardware/mailserver-rancher#custom-mailserver-ssl-certificate
https://github.com/hardware/mailserver/blob/master/README.md#custom-certificates

**Comment by mervynlee94** [comment]
I sent you a message in Gitter. Thank you.

**Comment by mervynlee94** [comment]
I don't get it. Mailserver is started on Rancher before Traefik. I only can dig out SSL cert and key in /mnt/docker/mailserver/mail/ssl/selfsigned/. Then I configure Traefik and insert the cert and key value, doesn't work. I am blur about the Let's encrypt generated by Traefik, because it doesn't. Please help=(

**Comment by mervynlee94** [comment]
I get ERR connection refused when I try to suft webmail and so on with https://. In Traefik container, I got acme,json filled with those information on webmail, spam and postfixadmin sites.

**Comment by hardware** [comment]
> I am blur about the Let's encrypt generated by Traefik

I didn't find a way to share ssl certificates between Traefik and the mailserver with Rancher since @rawmind0 does not make it persistent. So you must use a custom certificat as stated in the readme.

https://github.com/rawmind0/alpine-traefik/issues/31
https://github.com/rawmind0/rancher-traefik

**Comment by mervynlee94** [comment]
Well actually, to make it works, must make sure that the http port is 80 and the https port is 443 instead of 8080 and 8443
